### ISSUE TITLE
Sonar is conflicting with auto1111 webui

### ISSUE THREAD

**Issue by dank12342** [Kahsolt/stable-diffusion-webui-sonar#12]
My extra-networks tab recently stopped working, I tried everything to get it working again, it was all fine one day, and not the other, I tried disabling extensions, and it worked, so I started to look for which extension was causing the conflict, and it was this one, when I disable it, the extra-networks tab starts working again, when I enable it, I can't access extra-networks through the tab/button, and its the only way to easily access it on Automatic1111, so I figured it was worthy of note.

**Comment by dank12342** [comment]
I uninstalled, reinstalled the extension, and the same problem persists.

As long as Sonar is enabled on my Auto1111 webUI, my extra-networks tab where you access LoRAs, hypernetworks, textual inversions, etc, will not open.

**Comment by Kahsolt** [comment]
🤔 Let me check it why...

**Comment by Kahsolt** [comment]
Well, this issue was once reported here #10, but nothing seems broken on my machine... I could still open the extras network tab and add any hypernets etc... I've tested my firefox, chrome and edge browsers, they are all ok 🤔

In my venv from webui, the `gradio.__version__ == '3.22.0'`, might this be gradio's bug (this fucking gradio is usually buggy...)?
Or, could you please check is there any console error logs in your browser (press `F12` and turn to `console` tab) when you click the dead buttons?

**Comment by dank12342** [comment]
No console errors, nothing happens, its like I'm not even pressing the button.

**Comment by Kahsolt** [comment]
Still not know why, could not reproduce this error and have no way to debug.
Leave it dangling for the moment.

**Comment by MichaelDavidGK** [comment]
> Still not know why, could not reproduce this error and have no way to debug. Leave it dangling for the moment.

webui now uses gradio 3.28.1

**Comment by illtellyoulater** [comment]
Could this approach still have any advantages or perhaps stuff like refiners and adefiner made this obsolete? I liked the process behind this though...

**Comment by Kahsolt** [comment]
> Could this approach still have any advantages or perhaps stuff like refiners and adefiner made this obsolete? I liked the process behind this though...

since SDXL and more samplers came out, sonar (the momentum mechanism) is not that notable now...

**Comment by Kahsolt** [comment]
as for a1111's updates, maybe it's not a problem now
