### ISSUE TITLE
[Bug] extension work as script :(

### ISSUE THREAD

**Issue by Rogal80** [Kahsolt/stable-diffusion-webui-sonar#8]
Hi any possibility to get a back option that we can enable sonar and still using script ?

**Comment by Kahsolt** [comment]
You'd prefer sonar to appear in the main panel as an AlwaysVisible, in order to work with other scripts? 🤔
I wonder what script you are to work together with.

Due to the commit supporting auto grid search, I moved it back from AlwaysVisible to the scripts drop down list.
Because it must take control over the whole process (hooking `run()` rather than just `preprocess()` and `postprocess()`) to draw **multiple** images with only **one** click of "Generate" button...

**Comment by Kahsolt** [comment]
There actually might be a chance for an extension to (not-so-easily) switch between `AlwaysVisible` mode and `dropdown scripts` mode, depending on the saved `ui-config.json` settings and webui restarts.

Even so, when working as a `AlwaysVisible` script, sonar cannot provide auto grid search 😥

**Comment by Rogal80** [comment]
for example :
- stylepile
- ABGremover
- x/y/z
- higres.fix.progressive

etc. - in both t2i, i2i

**Comment by Kahsolt** [comment]
Hi, see the checkbox now like `Move to AlwaysVisible panel at next webui reload` at the ui bottom, you can make it work with others ;)
